# Generated by Django 5.1.6 on 2025-03-11 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselor',
            old_name='availability',
            new_name='available_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='counselor',
            name='user_id',
        ),
        migrations.AddField(
            model_name='counselor',
            name='available_hours',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='counselor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_counselor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
