# Generated by Django 5.1.6 on 2025-03-13 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingapp', '0002_rename_availability_counselor_available_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_counselor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='counselor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
