# Generated by Django 5.1.6 on 2025-03-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingapp', '0004_add_availability_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='availability_end',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='availability_start',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
