# Generated by Django 5.1.6 on 2025-03-23 17:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingapp', '0006_counseloravailability_delete_counselor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='counseloravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='counseloravailability',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='counseloravailability',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='counseloravailability',
            name='day',
        ),
    ]
