# Generated by Django 5.1.7 on 2025-03-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingapp', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
