# Generated by Django 5.2.3 on 2025-06-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingapp', '0012_alter_user_is_student_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=10),
        ),
    ]
